### ISSUE TITLE
 practica de conjuntos y subconjustos de _rene_stgoo

### ISSUE THREAD

**Issue by 71santiago7** [SistemasTecTlaxiaco/practica-de-conjuntos-equipo-erick-ramos#2]
[conjuntos y subconjuntos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-conjuntos-equipo-erick-ramos/files/7318523/conjuntos.y.subconjuntos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
